---
specific_scripts:
  - src: misc/fix_rights_for_share.sh
  - src: darktable/darktable_custom.sh
  - src: darktable/pictures_tool.sh
  - src: darktable/purge_pictures.sh
  - src: darktable/copy_darktable_dev.sh
  - src: darktable/organize_pictures.sh
  - src: backup/backup_nas.sh
  - src: backup/backup_nas_family.sh
  - src: backup/X7.sh
