---
- include_tasks:
    file: setup_git_repo.yml
    apply:
      tags:
        - git
  loop: "{{ git_repositories }}"
  loop_control:
    loop_var: git_repo
  tags:
    - git

- include_tasks:
    file: setup_files.yml
    apply:
      tags:
        - setup_files
        - config_files
  vars:
    setup_files: "{{ config_files }}"
    setup_files_src_root: config
  tags:
    - setup_files
    - config_files

- include_tasks:
    file: setup_files.yml
    apply:
      tags:
        - setup_files
        - git_files
  vars:
    setup_files: "{{ git_files }}"
    setup_files_src_root: .git_repositories
  tags:
    - setup_files
    - git_files

- include_tasks:
    file: setup_files.yml
    apply:
      tags:
        - setup_files
        - scripts
  vars:
    setup_files: "{{ common_scripts + specific_scripts }}"
    setup_files_src_root: scripts
    setup_files_dest_root: "{{ user_home_dir }}/bin"
  tags:
    - setup_files
    - scripts
